import crypto from 'node:crypto';

const MAX_PROMPT=1800,MAX_IMAGE_BYTES=3_500_000,MAX_SEED=2147483647;
const inFlight=new Map(),completed=new Map();
function clean(v){return String(v||'').trim().replace(/\s+/g,' ').slice(0,MAX_PROMPT)}
function hash(v){return crypto.createHash('sha256').update(v).digest('hex')}
function seedFor(id){return parseInt(hash(id).slice(0,8),16)%(MAX_SEED+1)}
function fingerprint(prompt,size){return hash(`${size}\n${prompt}`)}
function enhance(prompt){const p=clean(prompt);if(!p)return p;return `${p}. Respecter exactement les sujets, attributs, relations et détails explicitement demandés, sans en ajouter ni en retirer. Si aucune autre origine, région ou esthétique n’est précisée, utiliser un rendu européen contemporain, naturel et photoréaliste, avec des proportions réalistes.`.slice(0,MAX_PROMPT)}
function json(res,status,body,extra={}){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');for(const[k,v]of Object.entries(extra))res.setHeader(k,v);res.end(JSON.stringify(body))}
function retryable(e){const s=Number(e?.status)||0;return!s||s===408||s===425||s===429||s>=500}
function modelFor(size){return size>=1024?'@cf/black-forest-labs/flux-1-schnell':'@cf/black-forest-labs/flux-2-klein-4b'}
function extractImage(p){return p?.result?.image||p?.image||p?.result?.result?.image||null}
async function cloudflare({prompt,size,requestId,fp}){const accountId=process.env.CLOUDFLARE_ACCOUNT_ID,token=process.env.CLOUDFLARE_API_TOKEN,gatewayId=process.env.CLOUDFLARE_AI_GATEWAY_ID||'default';if(!accountId||!token)return null;const model=modelFor(size),endpoint=`https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(accountId)}/ai/run/${model}`,headers={Authorization:`Bearer ${token}`,'cf-aig-gateway-id':gatewayId,'cf-aig-cache-key':`ia-perso:${hash(`${requestId}:${fp}`)}`,'cf-aig-cache-ttl':'3600','cf-aig-request-timeout':'30000','cf-aig-max-attempts':'1','cf-aig-collect-log':'true','cf-aig-collect-log-payload':'false','cf-aig-metadata':JSON.stringify({app:'ia-perso',requestId,size,model})};let body;if(model.includes('flux-2-klein')){body=new FormData();body.append('prompt',prompt);body.append('width',String(size));body.append('height',String(size));body.append('seed',String(seedFor(requestId)))}else{headers['Content-Type']='application/json';body=JSON.stringify({prompt,width:size,height:size,steps:4,seed:seedFor(requestId)})}const r=await fetch(endpoint,{method:'POST',headers,body}),text=await r.text();let p={};try{p=text?JSON.parse(text):{}}catch{}if(!r.ok||p?.success===false){const e=new Error(p?.errors?.[0]?.message||p?.error||`Cloudflare HTTP ${r.status}`);e.status=r.status;throw e}const image=extractImage(p);if(!image){const e=new Error('Cloudflare n’a retourné aucune image exploitable.');e.status=502;throw e}return{dataUri:`data:image/jpeg;base64,${image}`,provider:'cloudflare',model,size}}
function pollinationsUrl(prompt,size,requestId){const u=new URL(`https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}`);u.searchParams.set('width',String(size));u.searchParams.set('height',String(size));u.searchParams.set('model','flux');u.searchParams.set('safe','false');u.searchParams.set('seed',String(seedFor(requestId)));return u}
async function pollinations({prompt,size,requestId}){const r=await fetch(pollinationsUrl(prompt,size,requestId),{headers:{Accept:'image/*'},redirect:'follow'}),type=(r.headers.get('content-type')||'').split(';')[0].trim();if(!r.ok){const e=new Error(`Pollinations HTTP ${r.status}`);e.status=r.status;throw e}if(!type.startsWith('image/')){const e=new Error('Pollinations n’a pas renvoyé une image.');e.status=502;throw e}const bytes=Buffer.from(await r.arrayBuffer());if(!bytes.length||bytes.length>MAX_IMAGE_BYTES){const e=new Error(bytes.length?'Image trop volumineuse pour le transfert mobile.':'Pollinations a renvoyé une image vide.');e.status=502;throw e}return{dataUri:`data:${type};base64,${bytes.toString('base64')}`,provider:'pollinations',model:'flux',size,degraded:true}}
async function generate({prompt,size,requestId,fp}){const effectivePrompt=enhance(prompt);try{const out=await cloudflare({prompt:effectivePrompt,size,requestId,fp});if(out)return out}catch(e){if(!retryable(e))throw e;console.warn('cloudflare_transient_fallback',{requestId,status:e?.status||0,message:e?.message})}return pollinations({prompt:effectivePrompt,size:Math.min(size,768),requestId})}
function prune(){const now=Date.now();for(const[k,v]of completed)if(now-v.at>3600_000)completed.delete(k);if(completed.size>100)for(const[k]of[...completed.entries()].sort((a,b)=>a[1].at-b[1].at).slice(0,completed.size-100))completed.delete(k)}
export default async function handler(req,res){if(req.method!=='POST')return json(res,405,{error:'Méthode non autorisée.'},{Allow:'POST'});let body=req.body;if(typeof body==='string')try{body=JSON.parse(body)}catch{body={}}const prompt=clean(body?.prompt),requestId=String(body?.requestId||'').trim(),size=Number(body?.size)>=1024?1024:512;if(!prompt)return json(res,400,{error:'Prompt vide.'});if(!/^[a-zA-Z0-9_-]{12,128}$/.test(requestId))return json(res,400,{error:'requestId invalide.'});const fp=fingerprint(prompt,size);prune();const old=completed.get(requestId);if(old){if(old.fp!==fp)return json(res,409,{error:'requestId déjà utilisé avec une autre demande.'});return json(res,200,{...old.value,cached:true})}const active=inFlight.get(requestId);if(active){if(active.fp!==fp)return json(res,409,{error:'requestId déjà utilisé avec une autre demande.'});try{return json(res,200,{...(await active.task),shared:true})}catch(e){return json(res,Number(e?.status)||502,{error:e?.message||'Échec de génération.'})}}const task=generate({prompt,size,requestId,fp});inFlight.set(requestId,{fp,task});try{const value=await task;completed.set(requestId,{at:Date.now(),fp,value});prune();return json(res,200,value)}catch(e){console.error('generation_failed',{requestId,message:e?.message,status:e?.status});return json(res,Number(e?.status)||502,{error:e?.message||'Échec de génération.'})}finally{inFlight.delete(requestId)}}
