const MAX_QUERY=500,FETCH_TIMEOUT_MS=1800,COMMONS_LIMIT=6,WEB_EXTRA_LIMIT=2,BLUESKY_LIMIT=5;
function clean(v){return String(v||'').trim().replace(/\s+/g,' ').slice(0,MAX_QUERY)}
function words(v){return(clean(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z0-9]+(?:-[a-z0-9]+)*/g)||[]).filter(w=>w.length>=3)}
function score(text,promptWords){const h=new Set(words(text));return promptWords.reduce((n,w)=>n+(h.has(w)?2:0),0)}
function minRel(ws){return ws.length>=4?4:2}
function uniq(items,limit){const seen=new Set(),out=[];for(const x of [...items].sort((a,b)=>b._score-a._score)){const k=x.landingUrl+'|'+x.thumbUrl;if(!x.landingUrl||!x.thumbUrl||seen.has(k))continue;seen.add(k);out.push(x);if(out.length>=limit)break}return out}
function pub(items){return items.map(({_score,...x})=>x)}
function json(res,status,body,cache=false){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control',cache?'public, max-age=0, must-revalidate':'private, max-age=0, no-store');if(cache)res.setHeader('Vercel-CDN-Cache-Control','public, s-maxage=86400, stale-while-revalidate=604800, stale-if-error=604800');res.end(JSON.stringify(body))}
async function fetchJson(url,options={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),FETCH_TIMEOUT_MS);try{const r=await fetch(url,{...options,signal:c.signal});return{response:r,payload:await r.json().catch(()=>({}))}}catch{return{response:null,payload:{}}}finally{clearTimeout(t)}}
function english(q){const pairs=[[/\bchatons?\b/gi,'kitten'],[/\bchats?\b/gi,'cat'],[/\bchiens?\b/gi,'dog'],[/\bhommes?\b/gi,'man'],[/\bfemmes?\b/gi,'woman'],[/\btorse nu\b/gi,'shirtless'],[/\bcinquantaine\b/gi,'50s'],[/\bsoixantaine\b/gi,'60s'],[/\bgrisonnant(e)?s?\b/gi,'gray-haired'],[/\bcheveux\b/gi,'hair'],[/\bbarbe\b/gi,'beard'],[/\bdebout\b/gi,'standing'],[/\bassis(e)?\b/gi,'sitting'],[/\bcuisine\b/gi,'kitchen'],[/\bplage\b/gi,'beach'],[/\bmontagne\b/gi,'mountain'],[/\bcoucher du soleil\b/gi,'sunset'],[/\bphotographie\b/gi,'photograph'],[/\bphoto\b/gi,'photo'],[/\bréaliste\b/gi,'realistic']];let x=clean(q);for(const[p,r]of pairs)x=x.replace(p,r);return x===clean(q)?'':x}
async function commonsQuery(q,scoreWords){if(!q)return[];const u=new URL('https://commons.wikimedia.org/w/api.php');for(const[k,v]of Object.entries({action:'query',format:'json',formatversion:'2',generator:'search',gsrsearch:q,gsrnamespace:'6',gsrlimit:'40',prop:'imageinfo',iiprop:'url|user|mime',iiurlwidth:'640',origin:'*'}))u.searchParams.set(k,v);const{response,payload}=await fetchJson(u,{headers:{Accept:'application/json','Api-User-Agent':'IA-Perso/1.0'}});if(!response?.ok)return[];const allowed=new Set(['image/jpeg','image/png','image/webp']),m=minRel(scoreWords);return(payload?.query?.pages||[]).map(p=>{const i=p?.imageinfo?.[0],title=clean(String(p?.title||'').replace(/^File:/i,'')),landingUrl=String(i?.descriptionurl||''),thumbUrl=String(i?.thumburl||i?.url||''),r=score(title,scoreWords);if(!allowed.has(String(i?.mime||'').toLowerCase())||!/^https:\/\//i.test(landingUrl)||!/^https:\/\//i.test(thumbUrl)||r<m)return null;return{id:'commons-'+(p.pageid||thumbUrl),title:title||'Référence Wikimedia Commons',creator:i?.user||'Wikimedia Commons',source:'Wikimedia Commons',sourceType:'commons',license:'Média libre — voir la fiche source',landingUrl,thumbUrl,sensitive:false,sensitivity:[],_score:r+4}}).filter(Boolean)}
async function commonsRefs(q,pw){const en=english(q),sw=[...new Set([...pw,...words(en)])],a=await commonsQuery(q,sw);if(a.length>=COMMONS_LIMIT||!en)return uniq(a,COMMONS_LIMIT);return uniq([...a,...await commonsQuery(en,sw)],COMMONS_LIMIT)}
async function openverse(q,pw){const u=new URL('https://api.openverse.org/v1/images/');u.searchParams.set('q',q);u.searchParams.set('page_size','20');u.searchParams.set('filter_dead','true');u.searchParams.set('mature','true');const{response,payload}=await fetchJson(u,{headers:{Accept:'application/json','User-Agent':'IA-Perso/1.0'}});if(!response?.ok)return[];const m=minRel(pw);return(payload?.results||[]).map(x=>{const landingUrl=String(x?.foreign_landing_url||x?.detail_url||''),thumbUrl=String(x?.thumbnail||''),title=clean(x?.title)||'Référence Openverse',tags=(x?.tags||[]).slice(0,12).map(t=>clean(t?.name||t)).join(' '),r=score(title+' '+tags+' '+(x?.creator||''),pw);if(!/^https:\/\//i.test(landingUrl)||!/^https:\/\//i.test(thumbUrl)||r<m)return null;return{id:'openverse-'+(x?.id||thumbUrl),title,creator:clean(x?.creator)||'Openverse',source:'Openverse',sourceType:'openverse',license:clean(x?.license)||'',landingUrl,thumbUrl,sensitive:Boolean(x?.mature),sensitivity:Array.isArray(x?.unstable__sensitivity)?x.unstable__sensitivity:[],_score:r+1}}).filter(Boolean)}
async function google(q,pw){const key=process.env.GOOGLE_CSE_API_KEY,cx=process.env.GOOGLE_CSE_CX;if(!key||!cx)return[];const u=new URL('https://customsearch.googleapis.com/customsearch/v1');for(const[k,v]of Object.entries({key,cx,q,searchType:'image',num:'8',safe:'off',filter:'0',hl:'fr',gl:'fr',lr:'lang_fr',cr:'countryFR'}))u.searchParams.set(k,v);const{response,payload}=await fetchJson(u,{headers:{Accept:'application/json'}});if(!response?.ok)return[];const m=minRel(pw);return(payload?.items||[]).map((x,n)=>{const landingUrl=x.image?.contextLink||x.link||'',thumbUrl=x.image?.thumbnailLink||x.link||'',r=score((x.title||'')+' '+(x.snippet||''),pw);if(!/^https:\/\//i.test(landingUrl)||!/^https:\/\//i.test(thumbUrl)||r<m)return null;return{id:'google-'+(x.cacheId||n),title:x.title||'Référence Google Images',creator:x.displayLink||'Google Images',source:'Google Images',sourceType:'google',license:'',landingUrl,thumbUrl,sensitive:false,sensitivity:[],_score:r}}).filter(Boolean)}
function blocked(post){const b=new Set(['!hide','!no-unauthenticated','!takedown']),ls=[...(post?.labels||[]),...(post?.author?.labels||[])];return ls.some(l=>b.has(String(l?.val||'')))}
async function bskyQuery(q,pw){if(!q)return[];const u=new URL('https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts');u.searchParams.set('q',q);u.searchParams.set('sort','top');u.searchParams.set('limit','30');const{response,payload}=await fetchJson(u,{headers:{Accept:'application/json'}});if(!response?.ok)return[];const out=[];for(const p of payload?.posts||[]){if(blocked(p))continue;const h=String(p?.author?.handle||''),rkey=String(p?.uri||'').split('/').pop(),landingUrl=h&&rkey?`https://bsky.app/profile/${encodeURIComponent(h)}/post/${encodeURIComponent(rkey)}`:'';if(!landingUrl)continue;const text=clean(p?.record?.text),imgs=[...(p?.embed?.images||[]),...(p?.embed?.media?.images||[])];for(const im of imgs){const thumbUrl=String(im?.thumb||im?.fullsize||''),alt=clean(im?.alt),r=score(text+' '+alt,pw);if(!/^https:\/\//i.test(thumbUrl)||r<2)continue;out.push({id:'bsky-'+(p?.cid||thumbUrl),title:alt||text||'Référence Bluesky',creator:p?.author?.displayName||h||'Bluesky',source:'Bluesky',sourceType:'bluesky',license:'',landingUrl,thumbUrl,sensitive:false,sensitivity:[],_score:r+(alt?2:0)})}}return out}
async function bsky(q,pw){const en=english(q),sw=[...new Set([...pw,...words(en)])],a=await bskyQuery(q,sw);if(a.length>=BLUESKY_LIMIT||!en)return uniq(a,BLUESKY_LIMIT);return uniq([...a,...await bskyQuery(en,sw)],BLUESKY_LIMIT)}
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{error:'Méthode non autorisée.'});const q=clean(req.query?.q);if(!q)return json(res,200,{results:[],commons:[],web:[],bluesky:[]});try{const pw=[...new Set(words(q))],en=english(q),scoreWords=[...new Set([...pw,...words(en)])];const[commons,open,bskyItems]=await Promise.all([commonsRefs(q,pw),openverse(en||q,scoreWords),bsky(q,pw)]);let extras=uniq(open,WEB_EXTRA_LIMIT);if(extras.length<WEB_EXTRA_LIMIT)extras=uniq([...extras,...await google(q,pw)],WEB_EXTRA_LIMIT);const commonPublic=pub(commons),web=pub(extras),bluesky=pub(bskyItems),results=[...commonPublic,...web,...bluesky];return json(res,200,{results,commons:commonPublic,web,openverse:pub(open),bluesky,providers:['wikimedia-commons','openverse','google-images-fr','bluesky-public'],limits:{commons:COMMONS_LIMIT,web:WEB_EXTRA_LIMIT,bluesky:BLUESKY_LIMIT}},results.length>0)}catch(e){console.error('reference_search_failed',{message:e?.message});return json(res,200,{results:[],commons:[],web:[],bluesky:[]})}}
